language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

env:
  - DEPS=normal
  - DEPS=highest
  - DEPS=lowest

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.composer/cache
  - $HOME/.php-cs-fixer

notifications:
  email: false
  slack:
    secure: ixWu6kWtNIlzzdImpu4MdvGYpA6ZPp/dQpMAp6FDO2oHHB55J9ossBYtVtBXPCDs9OxqfQl2yqbE+TkhfIfkZqIbhvX2+CiIomvYSKZDvryUlCfbfV29behmSVIVYvg3b8Tba+nAyZeJA2guUyAy02WGr3n4I+PDgZC3Wa/mv94=

before_install:
  - travis_retry composer selfupdate --preview
  # Disable xdebug for faster Composer
  - if [ "${TRAVIS_PHP_VERSION}" != "7.1" ]; then phpenv config-rm xdebug.ini; fi

install:
  - if [ "$DEPS" = "normal" ]; then travis_retry composer install --no-interaction; fi;
  - if [ "$DEPS" = "highest" ]; then travis_retry composer update --no-interaction; fi;
  - if [ "$DEPS" = "lowest" ]; then travis_retry composer update --no-interaction --prefer-lowest --prefer-stable; fi;

before_script:
  # Enable xdebug for code coverage
  - echo "zend_extension=xdebug.so" > xdebug.ini
  - phpenv config-add xdebug.ini

script:
  - ./vendor/bin/phpunit --stop-on-error --stop-on-failure --coverage-text

  # Disable xdebug for faster php-cs-fixer
  - phpenv config-rm xdebug.ini
  - if [ "$DEPS" = "normal" ]; then ./vendor/bin/php-cs-fixer fix --cache-file $HOME/.php-cs-fixer/.php_cs.cache --dry-run --diff --no-interaction --verbose; fi
